from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('pms_series', src, depend = ['PKG_USING_PMS_SERIES_SAMPLE'], CPPPATH = CPPPATH)

Return('group')
