from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('pms_series', src, depend = ['PKG_USING_PMS_SERIES'], CPPPATH = CPPPATH)

Return('group')
